apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-kube-system
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  #name: edit
subjects:
  - kind: ServiceAccount
    name: tiller-kube-system
    namespace: kube-system
